version: '3'

services:

  # Conteneur base de données
  db:
    image: mongo
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      # Ce volume permettra de préserver les données si la base de données doit évoluer. Ici, on
      # se base uniquement sur les données dans le dump, et ce volume n'est pas forcément nécessaire
      - ./data:/data/db
      # On monte le dump de la base de données dans un dossier du conteneur
      - ./dump/test:/dump/
      # On monte le script mongorestore.sh dans le dossier /docker-entrypoint-initdb.d, qui sera
      # lancé automatiquement au démarrage du conteneur.
      # Ce dossier d'entrypoint est une convention Docker, qui est au moins respectée pour tous les
      # conteneurs de base de données
      - ./dump/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh:ro
  # Conteneur frontend
  front:
    container_name: front-exo
    build: ./front/.
    # depends_on:
    #   - backv2
    ports:
      - 80:80
  # Conteneur back  
  back:
    container_name: back-exo
    build: ./back/.
    # depends_on:
    #   - db
    environment:
      - PORT=8080
      - MONGO_HOST=db
    ports:
      - 8080:8080

  # Conteneur Mongo Express
  mongo-expressv2:
    image: mongo-express
    restart: always
    depends_on:
      - db
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      # - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}

